// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/synccond/philosophers/main.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./internal/synccond/philosophers/mocks/mock_main.go -source ./internal/synccond/philosophers/main.go
//

// Package mocks is a generated GoMock package.
package mocks
